name: Run Pytest with uv

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Check formatting
        id: check-formatting
        run: |
          uv run black --check --diff src/ tests/
        continue-on-error: true

      - if: ${{ steps.check-formatting.outcome == 'failure' }}
        run: echo -e "Formatting check failed. Please run 'uv run black src/ tests/' to fix."

      - name: Run tests
        run: |
          uv run pytest tests
